# YAML
---

# Current observations
station: 'KDTO'

# Three-letter abbreviations are available at, among other places: 
# http://weather.rap.ucar.edu/radar/
radar_station: &r_abbr 'FWS'
ridgeii_radar_station: 'KFWS'

# office call signs found at 
# https://en.wikipedia.org/wiki/List_of_National_Weather_Service_Weather_Forecast_Offices
# or the WFO SID column at  https://www.roc.noaa.gov/WSR88D/Program/NetworkSites.aspx
nws_abbr: 'FWD'

# Forecast zone:
# 
forecast_zone: 'TXZ103'

# GOES information: https://www.star.nesdis.noaa.gov/GOES/index.php
goes_sector: 'sp'
goes_res: '2400x2400'
goes_sat: '16'

# River gauge abbreviations available at: https://water.weather.gov/ahps/
river_gauge_abbr: 'cart2'

# Hazardous weather outlook URL path portion (shouldn't need to change):
hwo_site: 'DDC'

# Forecast lon/lat values (i.e. your house or office)
lon: -97.07
lat: 33.16

# Time zone needs to be compatible with the TZ database:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: 'America/Chicago'

# Be sure the directory is universally writable, if you plan to schedule this
# script to run.
output_dir: '/tmp/'

# County and Zones maps by state: https://alerts.weather.gov/
# (Zone maps also available at: https://www.weather.gov/pimar/PubZone )
# Note these counties must be specifically named according to NWS spellings
# But feel free to add other states and counties as needed!
counties_for_alerts:
  'TX': ['Denton', 'Wise', 'Dallas', 'Tarrant', 'Cooke', 'Montague']
  # 'AL': ['Madison', 'Limestone']
  # 'KY': ['Daviess']


# Convective outlook resources:
convective: !!python/dict
  'url': 'https://www.spc.noaa.gov/products/outlook/'
  'today': 'day1otlk_0100_prt.gif'
  'html': 'day1otlk_0100_prt.html'
  'thumbnail': 'day1otlk_sm.gif'

radar_layers:
  r_abbr: *r_abbr
  'counties': 'County/Short/{r_abbr}_County_Short.gif'
  'highways': 'Highways/Short/{r_abbr}_Highways_Short.gif'
  'sml_cities': 'Cities/Short/{r_abbr}_City_25K_Short.gif'
  'med_cities': 'Cities/Short/{r_abbr}_City_250K_Short.gif'
  'lrg_cities': 'Cities/Short/{r_abbr}_City_1M_Short.gif'
  'ring': 'RangeRings/Short/{r_abbr}_RangeRing_Short.gif'
  'rivers': 'Rivers/Short/{r_abbr}_Rivers_Short.gif'
  'topo': 'Topo/Short/{r_abbr}_Topo_Short.jpg'

image_dir: 'static/photos'

units:
  # Distance: miles, kilometers
  'distance': 'miles'
  # Temperature: F, C
  'temperature': 'F'
  # Velocity: kph, mph, m_s-1
  'velocity': 'mph'
  # Pressure: inHg, Pa, mb, kPa
  'pressure': 'kPa'
  # Percent (TODO) either as 0-100 or 0-1
  'percent': '%'
...
